configs = {
    "transformer": {
        "flickr": {
            "num_layers": 5,
            "num_heads": 4,
            "ego_size": 256,
            "hidden_size": 64,
            "input_dropout": 0.4,
            "hidden_dropout": 0.3,
            "warmup": 4000,
            "weight_decay": 0.0005,
        },
        "reddit": {
            "num_layers": 5,
            "num_heads": 4,
            "ego_size": 256,
            "hidden_size": 64,
            "input_dropout": 0.3,
            "hidden_dropout": 0.4,
            "warmup": 10000,
            "weight_decay": 0.005,
        },
        "yelp": {
            "num_layers": 3,
            "num_heads": 1,
            "ego_size": 128,
            "hidden_size": 256,
            "input_dropout": 0.1,
            "hidden_dropout": 0.3,
            "warmup": 10000,
            "weight_decay": 0.0005,
        },
        "amazon": {
            "num_layers": 5,
            "num_heads": 4,
            "ego_size": 128,
            "hidden_size": 128,
            "input_dropout": 0.1,
            "hidden_dropout": 0.2,
            "warmup": 10000,
            "weight_decay": 0.0,
        },
    },
    "gcn": {
        "flickr": {
            "num_layers": 5,
            "ego_size": 256,
            "hidden_size": 128,
            "input_dropout": 0.0,
            "hidden_dropout": 0.3,
            "lr": 0.01,
            "weight_decay": 0.0005,
        },
        "reddit": {
            "num_layers": 5,
            "ego_size": 256,
            "hidden_size": 128,
            "input_dropout": 0.0,
            "hidden_dropout": 0.3,
            "lr": 0.001,
            "weight_decay": 0.0,
        },
        "yelp": {
            "num_layers": 3,
            "ego_size": 128,
            "hidden_size": 512,
            "input_dropout": 0.0,
            "hidden_dropout": 0.1,
            "lr": 0.01,
            "weight_decay": 0.0,
        },
        "amazon": {
            "num_layers": 4,
            "ego_size": 128,
            "hidden_size": 512,
            "input_dropout": 0.0,
            "hidden_dropout": 0.2,
            "lr": 0.001,
            "weight_decay": 0.0,
        },
    },
    "sage": {
        "flickr": {
            "num_layers": 5,
            "ego_size": 256,
            "hidden_size": 512,
            "input_dropout": 0.2,
            "hidden_dropout": 0.3,
            "lr": 0.001,
            "weight_decay": 0.0,
        },
        "reddit": {
            "num_layers": 5,
            "ego_size": 256,
            "hidden_size": 512,
            "input_dropout": 0.2,
            "hidden_dropout": 0.3,
            "lr": 0.001,
            "weight_decay": 0.0,
        },
        "yelp": {
            "num_layers": 3,
            "ego_size": 128,
            "hidden_size": 512,
            "input_dropout": 0.0,
            "hidden_dropout": 0.1,
            "lr": 0.01,
            "weight_decay": 0.0,
        },
        "amazon": {
            "num_layers": 4,
            "ego_size": 64,
            "hidden_size": 512,
            "input_dropout": 0.1,
            "hidden_dropout": 0.1,
            "lr": 0.001,
            "weight_decay": 0.0,
        },
    },
    "gat": {
        "flickr": {
            "num_layers": 5,
            "num_heads": 4,
            "ego_size": 256,
            "hidden_size": 512,
            "input_dropout": 0.2,
            "hidden_dropout": 0.1,
            "lr": 0.001,
            "weight_decay": 0.0,
        },
        "reddit": {
            "num_layers": 5,
            "num_heads": 4,
            "ego_size": 256,
            "hidden_size": 512,
            "input_dropout": 0.2,
            "hidden_dropout": 0.2,
            "lr": 0.001,
            "weight_decay": 0.0,
        },
        "yelp": {
            "num_layers": 4,
            "num_heads": 4,
            "ego_size": 128,
            "hidden_size": 1024,
            "input_dropout": 0.0,
            "hidden_dropout": 0.2,
            "lr": 0.001,
            "weight_decay": 0.0005,
        },
        "amazon": {
            "num_layers": 5,
            "num_heads": 4,
            "ego_size": 64,
            "hidden_size": 1024,
            "input_dropout": 0.2,
            "hidden_dropout": 0.1,
            "lr": 0.001,
            "weight_decay": 0.0,
        },
    }
}